//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Shoe", "ShoeDescriptionShoe", "ShoeDescription", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(MyShoeShoes.ShoeDescription), "Shoe", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(MyShoeShoes.Shoe), true)]

#endregion

namespace MyShoeShoes
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class ShoeContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new ShoeContainer object using the connection string found in the 'ShoeContainer' section of the application configuration file.
        /// </summary>
        public ShoeContainer() : base("name=ShoeContainer", "ShoeContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ShoeContainer object.
        /// </summary>
        public ShoeContainer(string connectionString) : base(connectionString, "ShoeContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new ShoeContainer object.
        /// </summary>
        public ShoeContainer(EntityConnection connection) : base(connection, "ShoeContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Shoe> Shoes
        {
            get
            {
                if ((_Shoes == null))
                {
                    _Shoes = base.CreateObjectSet<Shoe>("Shoes");
                }
                return _Shoes;
            }
        }
        private ObjectSet<Shoe> _Shoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ShoeDescription> ShoeDescriptions
        {
            get
            {
                if ((_ShoeDescriptions == null))
                {
                    _ShoeDescriptions = base.CreateObjectSet<ShoeDescription>("ShoeDescriptions");
                }
                return _ShoeDescriptions;
            }
        }
        private ObjectSet<ShoeDescription> _ShoeDescriptions;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Shoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToShoes(Shoe shoe)
        {
            base.AddObject("Shoes", shoe);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ShoeDescriptions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToShoeDescriptions(ShoeDescription shoeDescription)
        {
            base.AddObject("ShoeDescriptions", shoeDescription);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Shoe", Name="Shoe")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    [KnownTypeAttribute(typeof(Shoecolor))]
    public partial class Shoe : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Shoe object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="shoeType">Initial value of the ShoeType property.</param>
        /// <param name="shoeDescriptionId">Initial value of the ShoeDescriptionId property.</param>
        public static Shoe CreateShoe(global::System.Int32 id, ShoeType shoeType, global::System.Int32 shoeDescriptionId)
        {
            Shoe shoe = new Shoe();
            shoe.Id = id;
            shoe.ShoeType = StructuralObject.VerifyComplexObjectIsNotNull(shoeType, "ShoeType");
            shoe.ShoeDescriptionId = shoeDescriptionId;
            return shoe;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ShoeDescriptionId
        {
            get
            {
                return _ShoeDescriptionId;
            }
            set
            {
                OnShoeDescriptionIdChanging(value);
                ReportPropertyChanging("ShoeDescriptionId");
                _ShoeDescriptionId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ShoeDescriptionId");
                OnShoeDescriptionIdChanged();
            }
        }
        private global::System.Int32 _ShoeDescriptionId;
        partial void OnShoeDescriptionIdChanging(global::System.Int32 value);
        partial void OnShoeDescriptionIdChanged();

        #endregion
        #region Complex Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmComplexPropertyAttribute()]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Content)]
        [XmlElement(IsNullable=true)]
        [SoapElement(IsNullable=true)]
        [DataMemberAttribute()]
        public ShoeType ShoeType
        {
            get
            {
                _ShoeType = GetValidValue(_ShoeType, "ShoeType", false, _ShoeTypeInitialized);
                _ShoeTypeInitialized = true;
                return _ShoeType;
            }
            set
            {
                OnShoeTypeChanging(value);
                ReportPropertyChanging("ShoeType");
                _ShoeType = SetValidValue(_ShoeType, value, "ShoeType");
                _ShoeTypeInitialized = true;
                ReportPropertyChanged("ShoeType");
                OnShoeTypeChanged();
            }
        }
        private ShoeType _ShoeType;
        private bool _ShoeTypeInitialized;
        partial void OnShoeTypeChanging(ShoeType value);
        partial void OnShoeTypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Shoe", "ShoeDescriptionShoe", "ShoeDescription")]
        public ShoeDescription ShoeDescription
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ShoeDescription>("Shoe.ShoeDescriptionShoe", "ShoeDescription").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ShoeDescription>("Shoe.ShoeDescriptionShoe", "ShoeDescription").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ShoeDescription> ShoeDescriptionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ShoeDescription>("Shoe.ShoeDescriptionShoe", "ShoeDescription");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ShoeDescription>("Shoe.ShoeDescriptionShoe", "ShoeDescription", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Shoe", Name="Shoecolor")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Shoecolor : Shoe
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Shoecolor object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="shoeType">Initial value of the ShoeType property.</param>
        /// <param name="shoeDescriptionId">Initial value of the ShoeDescriptionId property.</param>
        /// <param name="color">Initial value of the Color property.</param>
        public static Shoecolor CreateShoecolor(global::System.Int32 id, ShoeType shoeType, global::System.Int32 shoeDescriptionId, global::System.String color)
        {
            Shoecolor shoecolor = new Shoecolor();
            shoecolor.Id = id;
            shoecolor.ShoeType = StructuralObject.VerifyComplexObjectIsNotNull(shoeType, "ShoeType");
            shoecolor.ShoeDescriptionId = shoeDescriptionId;
            shoecolor.Color = color;
            return shoecolor;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Color
        {
            get
            {
                return _Color;
            }
            set
            {
                OnColorChanging(value);
                ReportPropertyChanging("Color");
                _Color = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Color");
                OnColorChanged();
            }
        }
        private global::System.String _Color;
        partial void OnColorChanging(global::System.String value);
        partial void OnColorChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Shoe", Name="ShoeDescription")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ShoeDescription : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ShoeDescription object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="shoeDetails">Initial value of the ShoeDetails property.</param>
        /// <param name="shoeShort">Initial value of the ShoeShort property.</param>
        /// <param name="shoeType">Initial value of the ShoeType property.</param>
        public static ShoeDescription CreateShoeDescription(global::System.Int32 id, global::System.String shoeDetails, global::System.String shoeShort, global::System.String shoeType)
        {
            ShoeDescription shoeDescription = new ShoeDescription();
            shoeDescription.Id = id;
            shoeDescription.ShoeDetails = shoeDetails;
            shoeDescription.ShoeShort = shoeShort;
            shoeDescription.ShoeType = shoeType;
            return shoeDescription;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ShoeDetails
        {
            get
            {
                return _ShoeDetails;
            }
            set
            {
                OnShoeDetailsChanging(value);
                ReportPropertyChanging("ShoeDetails");
                _ShoeDetails = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ShoeDetails");
                OnShoeDetailsChanged();
            }
        }
        private global::System.String _ShoeDetails;
        partial void OnShoeDetailsChanging(global::System.String value);
        partial void OnShoeDetailsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ShoeShort
        {
            get
            {
                return _ShoeShort;
            }
            set
            {
                OnShoeShortChanging(value);
                ReportPropertyChanging("ShoeShort");
                _ShoeShort = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ShoeShort");
                OnShoeShortChanged();
            }
        }
        private global::System.String _ShoeShort;
        partial void OnShoeShortChanging(global::System.String value);
        partial void OnShoeShortChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ShoeType
        {
            get
            {
                return _ShoeType;
            }
            set
            {
                OnShoeTypeChanging(value);
                ReportPropertyChanging("ShoeType");
                _ShoeType = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ShoeType");
                OnShoeTypeChanged();
            }
        }
        private global::System.String _ShoeType;
        partial void OnShoeTypeChanging(global::System.String value);
        partial void OnShoeTypeChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Shoe", "ShoeDescriptionShoe", "Shoe")]
        public EntityCollection<Shoe> Shoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Shoe>("Shoe.ShoeDescriptionShoe", "Shoe");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Shoe>("Shoe.ShoeDescriptionShoe", "Shoe", value);
                }
            }
        }

        #endregion
    }

    #endregion
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="Shoe", Name="ShoeType")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class ShoeType : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ShoeType object.
        /// </summary>
        /// <param name="hakken">Initial value of the Hakken property.</param>
        /// <param name="laarzen">Initial value of the Laarzen property.</param>
        /// <param name="slippers">Initial value of the Slippers property.</param>
        /// <param name="gympies">Initial value of the Gympies property.</param>
        public static ShoeType CreateShoeType(global::System.Int32 hakken, global::System.Int32 laarzen, global::System.Int32 slippers, global::System.Int32 gympies)
        {
            ShoeType shoeType = new ShoeType();
            shoeType.Hakken = hakken;
            shoeType.Laarzen = laarzen;
            shoeType.Slippers = slippers;
            shoeType.Gympies = gympies;
            return shoeType;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Hakken
        {
            get
            {
                return _Hakken;
            }
            set
            {
                OnHakkenChanging(value);
                ReportPropertyChanging("Hakken");
                _Hakken = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Hakken");
                OnHakkenChanged();
            }
        }
        private global::System.Int32 _Hakken;
        partial void OnHakkenChanging(global::System.Int32 value);
        partial void OnHakkenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Laarzen
        {
            get
            {
                return _Laarzen;
            }
            set
            {
                OnLaarzenChanging(value);
                ReportPropertyChanging("Laarzen");
                _Laarzen = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Laarzen");
                OnLaarzenChanged();
            }
        }
        private global::System.Int32 _Laarzen;
        partial void OnLaarzenChanging(global::System.Int32 value);
        partial void OnLaarzenChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Slippers
        {
            get
            {
                return _Slippers;
            }
            set
            {
                OnSlippersChanging(value);
                ReportPropertyChanging("Slippers");
                _Slippers = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Slippers");
                OnSlippersChanged();
            }
        }
        private global::System.Int32 _Slippers;
        partial void OnSlippersChanging(global::System.Int32 value);
        partial void OnSlippersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Gympies
        {
            get
            {
                return _Gympies;
            }
            set
            {
                OnGympiesChanging(value);
                ReportPropertyChanging("Gympies");
                _Gympies = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Gympies");
                OnGympiesChanged();
            }
        }
        private global::System.Int32 _Gympies;
        partial void OnGympiesChanging(global::System.Int32 value);
        partial void OnGympiesChanged();

        #endregion
    }

    #endregion
    
}
